### ISSUE TITLE
Could you please add support for Office 365 China version:

### ISSUE THREAD

**Issue by FlashIvano** [mguessan/davmail#341]
Clients Settings

```yaml
POP:
  服务器名称: 
    Outlook Global: outlook.office365.com
    Outlook 21Vianet: partner.outlook.cn
  端口: 995
  加密方法: SSL

IMAP:
  服务器名称:
    Outlook Global: outlook.office365.com
    Outlook 21Vianet: partner.outlook.cn
  端口: 993
  加密方法: SSL

SMTP:
  服务器名称:
    Outlook Global: smtp.office365.com
    Outlook 21Vianet: smtp.partner.outlook.cn
  端口: 587
  加密方法: StartTLS
```

OAUTH Settings

```yaml
Outlook Global: 
  ews_url: https://outlook.office365.com/EWS/Exchange.asmx
  permission_url: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/common/oauth2/v2.0/token
Outlook 21Vianet:
  ews_url: https://partner.outlook.cn/EWS/Exchange.asmx
  permission_url: https://login.chinacloudapi.cn/common/oauth2/v2.0/authorize
  token_url: https://login.chinacloudapi.cn/common/oauth2/v2.0/token
```
